/* Page-load beacon for shir-openu.github.io
 *
 * WHAT THIS IS
 * ------------
 * GitHub gives no analytics for Pages: repository "traffic" is github.com page
 * views and git clones, and says nothing about anyone opening the site itself.
 * So a link from a Zenodo record straight to a page here was, until this file,
 * completely uncountable. Each page load posts one row to Supabase and that is
 * the whole mechanism.
 *
 * WHAT IT RECORDS
 * ---------------
 * the page (host, path, title), the referrer - which is the field that answers
 * "did they come from Zenodo?" - the browser timezone and UTC offset (a country
 * estimate without touching an IP address), screen size, language, and a random
 * id kept in sessionStorage.
 *
 * CLICKS OUT (added 11 September 2026)
 * -----------------------------------
 * A second kind of row, path "/__click/zenodo/...", "/__click/file/..." or
 * "/__click/out/...", written when a visitor clicks a link that leaves the page.
 * This is the only way a Zenodo download can ever carry a country: Zenodo itself
 * collects none, so the country has to be measured on the click before the
 * browser goes. Clicks are counted as clicks, never as page views.
 *
 * WHAT IT DOES NOT DO
 * -------------------
 * No cookie. No IP stored. No fingerprint. The session id lives in
 * sessionStorage, so it groups the pages of one visit and disappears with the
 * tab - it cannot follow anybody between visits or between sites.
 *
 * THE OWNER FLAG
 * --------------
 * The one thing kept between visits, and only for the site's own author: open
 * https://shir-openu.github.io/?owner=1 once in a browser and it writes
 * sv_owner into localStorage, so every later load from that browser posts
 * owner = true and is left out of the reader counts. ?owner=0 removes it. It
 * marks a browser, never a person: another browser, a phone, a private window
 * or cleared site data all start unflagged, and it cannot reach backwards to
 * rows already recorded.
 *
 * The key below is the PUBLIC anon key, the same one in js/core_fab.js. The
 * page_views table grants anon INSERT and nothing else, so this key can add a
 * row and can neither read the log nor change it.
 *
 * Generated by PRIMING_TOOLBOX/TOOLS/build_beacon.py - edit that, not this.
 */
(function () {
  try {
    if (location.protocol === 'file:') return;          // opened from disk
    var host = location.hostname;
    if (!host || host === 'localhost' || host === '127.0.0.1') return;

    var sid;
    try {
      sid = sessionStorage.getItem('sv_sid');
      if (!sid) {
        sid = Math.random().toString(36).slice(2) + Date.now().toString(36);
        sessionStorage.setItem('sv_sid', sid);
      }
    } catch (e) { sid = 'nostore'; }

    // Her own visits. localStorage, not sessionStorage: this one has to outlive
    // the tab, otherwise she would have to re-flag herself every single time.
    var own = false;
    try {
      var q = location.search || '';
      if (/[?&]owner=1(&|$)/.test(q)) localStorage.setItem('sv_owner', '1');
      else if (/[?&]owner=0(&|$)/.test(q)) localStorage.removeItem('sv_owner');
      own = localStorage.getItem('sv_owner') === '1';
    } catch (e) { own = false; }

    var tz = null, off = null;
    try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone || null; } catch (e) {}
    try { off = new Date().getTimezoneOffset(); } catch (e) {}

    var row = {
      site: host,
      path: (location.pathname || '/') + (location.search || ''),
      title: (document.title || '').slice(0, 300),
      referrer: document.referrer || null,
      session_id: sid,
      client_timezone: tz,
      client_utc_offset: off,
      client_started_at: new Date().toISOString(),
      screen: (window.screen ? screen.width + 'x' + screen.height : null),
      lang: navigator.language || null,
      owner: own
    };

    // fetch, not sendBeacon: sendBeacon cannot set the apikey header PostgREST
    // needs. keepalive lets it finish if the visitor navigates away at once.
    function send(r) {
      fetch('https://luhgdmzksitdkbysdfbr.supabase.co/rest/v1/page_views', {
        method: 'POST',
        mode: 'cors',
        keepalive: true,
        headers: {
          'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1aGdkbXprc2l0ZGtieXNkZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1MjU0MDMsImV4cCI6MjA4MDEwMTQwM30.kxiMmJE4N5U5pM-3d81URKCwZ5PSsE-19AIr5KWOMlQ',
          'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1aGdkbXprc2l0ZGtieXNkZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1MjU0MDMsImV4cCI6MjA4MDEwMTQwM30.kxiMmJE4N5U5pM-3d81URKCwZ5PSsE-19AIr5KWOMlQ',
          'Content-Type': 'application/json',
          'Prefer': 'return=minimal'
        },
        body: JSON.stringify([r])
      }).catch(function () { /* a page must never break because a count failed */ });
    }

    send(row);

    // CLICKS THAT LEAVE THE PAGE
    // --------------------------
    // Added 11 September 2026 on her instruction. The download counter on a Zenodo
    // record can never say where a download came from - Zenodo does not collect a
    // country for any view or download, and publishes none to anyone. But the click
    // on the link that LEADS there happens on this page, where the server already
    // measures the country from the request header. So the click is recorded here,
    // one row, the instant before the browser leaves.
    //
    // The row goes into page_views like every other row, with a path beginning
    // "/__click/". pages_usage_analysis.py splits those out, so a click is never
    // added to the page-view count: it is a different event and is counted once, as
    // itself. keepalive is what lets it survive the navigation that follows.
    var ZEN = /(^|\.)zenodo\.org$/i;
    var DOI = /(^|\.)doi\.org$|(^|\.)arxiv\.org$/i;
    var FILEY = /\.(pdf|zip|docx?|csv|xlsx?|pptx?|tgz)(\?|#|$)/i;
    document.addEventListener('click', function (ev) {
      try {
        var t = ev.target;
        var a = (t && t.closest) ? t.closest('a[href]') : null;
        if (!a) return;
        var u;
        try { u = new URL(a.getAttribute('href'), location.href); } catch (e) { return; }
        if (u.protocol !== 'http:' && u.protocol !== 'https:') return;
        // doi.org and arxiv.org are NOT zenodo. The paper pages link out to a
        // publisher DOI or an arXiv abstract, and filing those under "zenodo"
        // would put another publisher's traffic in her Zenodo column.
        var kind = ZEN.test(u.hostname) ? 'zenodo'
                 : (DOI.test(u.hostname) ? 'paper'
                 : (FILEY.test(u.pathname) ? 'file'
                 : (u.hostname !== host ? 'out' : null)));
        if (!kind) return;
        send({
          site: host,
          path: '/__click/' + kind + (location.pathname || '/'),
          title: ('click -> ' + u.href).slice(0, 300),
          referrer: location.href,
          session_id: sid,
          client_timezone: tz,
          client_utc_offset: off,
          client_started_at: new Date().toISOString(),
          screen: (window.screen ? screen.width + 'x' + screen.height : null),
          lang: navigator.language || null,
          owner: own
        });
      } catch (e) { /* a page must never break because a count failed */ }
    }, true);
  } catch (e) { /* same rule */ }
})();
