/* Page-load beacon for shir-openu.github.io
 *
 * WHAT THIS IS
 * ------------
 * GitHub gives no analytics for Pages: repository "traffic" is github.com page
 * views and git clones, and says nothing about anyone opening the site itself.
 * So a link from a Zenodo record straight to a page here was, until this file,
 * completely uncountable. Each page load posts one row to Supabase and that is
 * the whole mechanism.
 *
 * WHAT IT RECORDS
 * ---------------
 * the page (host, path, title), the referrer - which is the field that answers
 * "did they come from Zenodo?" - the browser timezone and UTC offset (a country
 * estimate without touching an IP address), screen size, language, and a random
 * id kept in sessionStorage.
 *
 * WHAT IT DOES NOT DO
 * -------------------
 * No cookie. No IP stored. No fingerprint. The session id lives in
 * sessionStorage, so it groups the pages of one visit and disappears with the
 * tab - it cannot follow anybody between visits or between sites.
 *
 * The key below is the PUBLIC anon key, the same one in js/core_fab.js. The
 * page_views table grants anon INSERT and nothing else, so this key can add a
 * row and can neither read the log nor change it.
 *
 * Generated by PRIMING_TOOLBOX/TOOLS/build_beacon.py - edit that, not this.
 */
(function () {
  try {
    if (location.protocol === 'file:') return;          // opened from disk
    var host = location.hostname;
    if (!host || host === 'localhost' || host === '127.0.0.1') return;

    var sid;
    try {
      sid = sessionStorage.getItem('sv_sid');
      if (!sid) {
        sid = Math.random().toString(36).slice(2) + Date.now().toString(36);
        sessionStorage.setItem('sv_sid', sid);
      }
    } catch (e) { sid = 'nostore'; }

    var tz = null, off = null;
    try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone || null; } catch (e) {}
    try { off = new Date().getTimezoneOffset(); } catch (e) {}

    var row = {
      site: host,
      path: (location.pathname || '/') + (location.search || ''),
      title: (document.title || '').slice(0, 300),
      referrer: document.referrer || null,
      session_id: sid,
      client_timezone: tz,
      client_utc_offset: off,
      client_started_at: new Date().toISOString(),
      screen: (window.screen ? screen.width + 'x' + screen.height : null),
      lang: navigator.language || null
    };

    // fetch, not sendBeacon: sendBeacon cannot set the apikey header PostgREST
    // needs. keepalive lets it finish if the visitor navigates away at once.
    fetch('https://luhgdmzksitdkbysdfbr.supabase.co/rest/v1/page_views', {
      method: 'POST',
      mode: 'cors',
      keepalive: true,
      headers: {
        'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1aGdkbXprc2l0ZGtieXNkZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1MjU0MDMsImV4cCI6MjA4MDEwMTQwM30.kxiMmJE4N5U5pM-3d81URKCwZ5PSsE-19AIr5KWOMlQ',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1aGdkbXprc2l0ZGtieXNkZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1MjU0MDMsImV4cCI6MjA4MDEwMTQwM30.kxiMmJE4N5U5pM-3d81URKCwZ5PSsE-19AIr5KWOMlQ',
        'Content-Type': 'application/json',
        'Prefer': 'return=minimal'
      },
      body: JSON.stringify([row])
    }).catch(function () { /* a page must never break because a count failed */ });
  } catch (e) { /* same rule */ }
})();
